79 convert the test site banner into a generic notification banner
uee-life/uee.life.next pull request #113
Opened 2024-07-09 19:46 UTC by CaptNemoUK

v0.1 of the new notification banner component.

Has 4 message types: error,warning,debug,info

Also has the option for a modal dialog box.

2024-07-09 22:13 UTC, CapnFlint requested changes
This needs to go into Dev, not Main.

2024-07-10 16:25 UTC, CaptNemoUK commented
Changes committed to remote branch and pull request changed to merge to dev.

2024-07-11 18:25 UTC, CapnFlint requested changes
Just a couple tweaks, but otherwise looks good!

2024-07-11 18:25 UTC, CapnFlint commented on package-lock.json
This shouldn't be here. Please remove it and re-commit, thanks!

2024-07-11 18:25 UTC, CapnFlint commented on app/layouts/default.vue
> +    <widgets-notification messageType="warning" messageText="Test Version - Data May Not Persist" :modality="true" v-if="config.public.test_env" >
If we aren't using/needing the modal here, remove the content and set modality to false please.

2024-07-11 18:49 UTC, CapnFlint approved these changes
LGTM!

2024-07-11 19:07 UTC, merged